### ISSUE TITLE
use nrgba instead of rgba image

### ISSUE THREAD

**Issue by makapuf** [xfmoulet/qoi#1]

**Comment by nigeltao** [comment]
Commit 111554b fixed this for *decoding*, but the *encoding* Go code still says:

```Go
// extract pixel
c := m.At(x, y)
c_r, c_g, c_b, c_a := c.RGBA()
px := pixel{byte(c_r >> 8), byte(c_g >> 8), byte(c_b >> 8), byte(c_a >> 8)}
```

The `c.RGBA()` means that you're encoding premultiplied alpha (as per the [`Color.RGBA`](https://pkg.go.dev/image/color#Color) godocs), not non-premultiplied alpha (what QOI uses).
